### ISSUE TITLE
Need a way to execute arbitrary redis commands on a connection from a `Pool`

### ISSUE THREAD

**Issue by dcormier** [go-redsync/redsync#112]
See issue #104 (which was closed as stale).

**Comment by dcormier** [comment]
If I were to use that `client` directly, I wouldn't be using a connection managed by the pool. I'm trying to reuse pooled connections.

**Comment by hjr265** [comment]
Based on the comment notification I received (I don't see the comment anymore) and that there is a cleaner way of interacting with the Redis client (without having to make changes to this package) I am going to go ahead and close this issue.

If you have any questions or anything to discuss further please feel free to continue discussing it here. I can reopen the issue if it makes sense.

Thanks!
