### ISSUE TITLE
Multi instance usage

### ISSUE THREAD

**Issue by gringus** [go-redsync/redsync#115]
In the [document](https://redis.io/docs/manual/patterns/distributed-locks/) `redsync` is based on we can read about having multiple independent masters yet all `redsync` examples are for a single Redis instance. I have a use case where I have multiple independent Redis instances (no clustering nor Sentinel) which I would like to use for _Distributed Lock Management_. How can I achieve that? Is that even possible? Any help would be appreciated.

**Comment by matyat** [comment]
I've no attachment to this project - just passing through. If you're using `github.com/redis/go-redis` you should be able to use the [`Ring`](https://redis.uptrace.dev/guide/ring.html) client, which is shards data across stand-alone Redis instances. I haven't tested it but it appears to be compatible with this pkg.

**Comment by matyat** [comment]
Sorry misread your question - that doesn't help if you want a distributed lock. Good luck!

**Comment by gringus** [comment]
@matyat No problem. After reading tests I came to something like this..
```
import redsyncredis "github.com/go-redsync/redsync/v4/redis"

pools := []redsyncredis.Pool{
  goredis.NewPool(redis.NewClient(...))),
  goredis.NewPool(redis.NewClien(...))),
  ...
}
rs := redsync.New(pools...)
...
```
The rest is the same. I believe something similar should be put in docs as people use this becasuse they want **DISTRIBUTED** Redis lock.
