### ISSUE TITLE
github.com/garyburd/redigo vs github.com/gomodule/redigo

### ISSUE THREAD

**Issue by mier85** [go-redsync/redsync#13]
The readme states, that the only dependency is github.com/gomodule/redigo, and yet the garyburd fork implementation is used.

It seems to me that you only use that implementation so you can return an interface instead of the actual implementation. But it doesn't really help. Before you had a hard dependency on gomodule/redigo, now you have a hard dependency on garyburd/redigo. One of them has a lot of supporters and will more likely stay up to date and the other one is a fork. 

Maybe it'd be better to switch back?

**Comment by cgst** [comment]
+1 for gomodule/redigo

**Comment by sheerun** [comment]
Yes please, for now I'm forking the project

**Comment by sheerun** [comment]
Oh, it actually works if I import this repository directly

**Comment by hjr265** [comment]
This is done and a new release has been created.
