### ISSUE TITLE
Crashed in mutex.go:112

### ISSUE THREAD

**Issue by kumangxxx** [go-redsync/redsync#14]
Hi, i got random crashes at mutex.go:112
this line: 
`defer conn.Close()`

any idea why ? could that because my redis was overwhelmed by requests that getting connection from pool return nil ?

thanks!

**Comment by hjr265** [comment]
@kumangxxx Do you have the stack trace?

**Comment by kumangxxx** [comment]
i do
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d387b]

goroutine 75698 [running]:
gopkg.in/redsync%2ev1.(*Mutex).acquire(0xc420a62300, 0x934ee0, 0xc4201df6e0, 0xc42035cc90, 0x2c, 0x1d4c9c0a500)
	/home/kumangkumeng/go/src/gopkg.in/redsync.v1/mutex.go:112 +0x5b
gopkg.in/redsync%2ev1.(*Mutex).Lock(0xc420a62300, 0x0, 0x0)
	/home/kumangkumeng/go/src/gopkg.in/redsync.v1/mutex.go:51 +0x15d
my-package/usecases.executeSchedule(0xc42045dc80, 0xc, 0xc420463120, 0x18, 0xc4201cca00, 0x4d, 0x5addd9a6, 0xc420807360, 0x98, 0xc42045dcfa, ...)
	/home/kumangkumeng/go/src/vouch-cron/usecases/runSchedule.go:150 +0x7f
my-package/usecases.runSchedule.func1(0xc4209ef000, 0xc420426300)
	/home/kumangkumeng/go/src/vouch-cron/usecases/runSchedule.go:45 +0x56
```
additional info, we're using redis cluster on AWS ElasticCache

**Comment by singchia** [comment]
@kumangxxx I guess you were not using [redigo's](https://godoc.org/github.com/gomodule/redigo/redis#Pool) Pool, since it promise always return a valid connection(won't be nil).

**Comment by slaveofcode** [comment]
in our case we're already use the pool but still got this error 

this issue happens when the amount of mutex `.Lock()` is getting larger
