### ISSUE TITLE
when i try lock，and get lock，finally i extend the lock；but  extend return error.

### ISSUE THREAD

**Issue by majintao** [go-redsync/redsync#144]

**Comment by majintao** [comment]
"msg":"Failed to extend lock:%!(EXTRA *redsync.ErrTaken=lock already taken, locked nodes: [0])",

**Comment by MouseSun846** [comment]
> "msg":"Failed to extend lock:%!(EXTRA *redsync.ErrTaken=lock already taken, locked nodes: [0])",
I have same problem, how do you solve it?

**Comment by nkarwa27** [comment]
Getting same error. Can you please share how it was fixed?

**Comment by MouseSun846** [comment]
Please check whether the lock is occupied

**Comment by MouseSun846** [comment]
Please check whether the lock is occupied

**Comment by nkarwa27** [comment]
Yes lock is occupied even after calling Unlock() and based on documentation it should expire after 8s which is not happening. Any reason for it? I am running go routines and different worker can try to access the same key.

**Comment by nkarwa27** [comment]
what to do if below fails?
// Release the lock so other processes or threads can obtain a lock.
	if ok, err := mutex.Unlock(); !ok || err != nil {
		panic("unlock failed")
	}
