### ISSUE TITLE
Redsync distributed lock has not been effective.

### ISSUE THREAD

**Issue by illaoiiiii** [go-redsync/redsync#145]
func (*InventoryServer) Sell(ctx context.Context, req *proto.SellInfo) (*emptypb.Empty, error) {
	client := goredislib.NewClient(&goredislib.Options{
               // my local redis host and port
		Addr: "192.168.137.128:6379",
	})
	pool := goredis.NewPool(client) // or, pool := redigo.NewPool(...)
	rs := redsync.New(pool)

	tx := global.DB.Begin()

	for _, goodInfo := range req.GoodsInfo {

		var inv model.Inventory

               // make the name  different
		mutex := rs.NewMutex(fmt.Sprintf("goods_%d", goodInfo.GoodsId))
		if err := mutex.Lock(); err != nil {
			return nil, status.Errorf(codes.Internal, "获取redis分布式锁异常")
		}

		if result := global.DB.Where(&model.Inventory{Goods: goodInfo.GoodsId}).First(&inv); result.RowsAffected == 0 {
			tx.Rollback() 
			return nil, status.Errorf(codes.InvalidArgument, "没有库存信息")
		}

		if inv.Stocks < goodInfo.Num {
			tx.Rollback()
			return nil, status.Errorf(codes.ResourceExhausted, "库存不足")
		}
		inv.Stocks -= goodInfo.Num
		tx.Save(&inv)

		if ok, err := mutex.Unlock(); !ok || err != nil {
			return nil, status.Errorf(codes.Internal, "释放redis分布式锁异常")
		}
	}
	tx.Commit() 
	return &emptypb.Empty{}, nil
}

**Comment by illaoiiiii** [comment]
my redis version in docker 
nacos/nacos-server                              latest    c056b930e4dd   3 weeks ago     816MB
consul                                          1.15      3295d4f4567b   4 weeks ago     155MB
redis                                           latest    3edbb69f9a49   17 months ago   117MB
mysql                                           latest    33037edcac9b   17 months ago   444MB
nginx                                           latest    41b0e86104ba   17 months ago   142MB

**Comment by rrxmzl** [comment]
你锁加错位置了,数据库事务提交才会对数据产生影响,tx.Commit()这里会有data race
```go
tx := global.DB.Begin()
mutex := rs.NewMutex(fmt.Sprintf("%s", <req唯一的标识>)) // 例如: req.GoodsInfo用来测试没问题
if err := mutex.Lock(); err != nil {
        return nil, status.Errorf(codes.Internal, "获取redis分布式锁异常")
}
for _, goodInfo := range req.GoodsInfo {

	var inv model.Inventory

           // make the name  different
	

	if result := global.DB.Where(&model.Inventory{Goods: goodInfo.GoodsId}).First(&inv); result.RowsAffected == 0 {
		tx.Rollback() 
		return nil, status.Errorf(codes.InvalidArgument, "没有库存信息")
	}

	if inv.Stocks < goodInfo.Num {
		tx.Rollback()
		return nil, status.Errorf(codes.ResourceExhausted, "库存不足")
	}
	inv.Stocks -= goodInfo.Num
	tx.Save(&inv)

	
}
tx.Commit() 
if ok, err := mutex.Unlock(); !ok || err != nil {
	return nil, status.Errorf(codes.Internal, "释放redis分布式锁异常")
}
return &emptypb.Empty{}, nil
```
