### ISSUE TITLE
What should be used to write / read data to Redis when using redsync?

### ISSUE THREAD

**Issue by SeanTolstoyevski** [go-redsync/redsync#146]
Hi,

We have a Redis server that multiple containers can access for writing/reading at the same time. We found redsync as a solution.
The package didn't seem clear enough to us (we are new to the Redis ecosystem). However, when we looked at the examples and docs, we could only see lock/unlock examples.

Which functions should be used to read and write to Redis when the mutex operations are complete? We are using `goredis/v9` as the Redis client.

We would be very happy if you could share an example with mutex that does reading/writing.

**Comment by rami-dabain** [comment]
redsync is only for the distributed locking
goredis is the library that does the read-write

https://github.com/redis/go-redis?tab=readme-ov-file#quickstart
