### ISSUE TITLE
No connection timeout

### ISSUE THREAD

**Issue by mier85** [go-redsync/redsync#15]
When the redis server is not available, it just keeps trying to connect forever. This should be configurable.

**Comment by hjr265** [comment]
@mier85 Isn't this something you can do when creating the pools?

[Dial](https://godoc.org/github.com/garyburd/redigo/redis#Dial) accepts DialOptions. You can may be use [DialConnectTimeout](https://godoc.org/github.com/garyburd/redigo/redis#DialConnectTimeout)?
