### ISSUE TITLE
go 版本依赖

### ISSUE THREAD

**Issue by shuqingzai** [go-redsync/redsync#157]
在 `v4.13.0` 开始需要 `go1.22+` ，这对于生产环境过于激进，是否可以跟随 Go [policy](https://go.dev/doc/devel/release#policy) 保持最新两个维护版本可用？这样可以使受众面更广

**Comment by carstendietrich** [comment]
We also use go-redsync in a project where we follow the Go policy and therefore support Go 1.21 and 1.22. Since I don't see a technical reason to bump to 1.22 we would appreciate it if this project could also follow this approach.
