### ISSUE TITLE
Failed to extend lock: lock already taken, locked nodes: [0]   false

### ISSUE THREAD

**Issue by a0709** [go-redsync/redsync#158]
func RedisDistributedLock() {
	// 创建 Redis 客户端
	client := redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
	})

	// 创建 redsync 实例
	pool := goredis.NewPool(client)
	rs := redsync.New(pool)
	// 创建一个 mutex 实例
	mutex := rs.NewMutex("my-global-mutex",
		redsync.WithExpiry(10*time.Second),
		redsync.WithTries(100))
	for {
		// 获取锁
		if err := mutex.Lock(); err != nil {
			fmt.Println("Lock wait")
			// time.Sleep(3 * time.Second)
			continue
		}
		fmt.Println("Lock acquired")

		// 设置续期周期（例如：每 2 秒续期一次）
		ticker := time.NewTicker(5 * time.Second)

		ctx, cancel := context.WithCancel(context.Background())

		// 启动一个 goroutine 进行续期
		go func() {
			defer ticker.Stop()
			for {
				select {
				case <-ticker.C:
					if ok, err := mutex.Extend(); !ok || err != nil {
						fmt.Println("Failed to extend lock:", err, " ", ok)
						continue
					}
					fmt.Println("Lock extended")
				case <-ctx.Done():
					fmt.Println("Lock extended end")
					return
				}
			}
		}()

		// 模拟一些业务逻辑
		time.Sleep(10 * time.Second)

		// 先停止续期，再释放锁
		cancel()

		// 释放锁
		if ok, err := mutex.Unlock(); !ok || err != nil {
			fmt.Println("Failed to release lock:", err)
		} else {
			fmt.Println("Lock released")
		}
	}
}

<img width="986" alt="image" src="https://github.com/user-attachments/assets/6b2abc31-2544-444c-8e80-1e496d1e7d79">

**Comment by a0709** [comment]
sorry, I know the reason.

**Comment by facumarcet** [comment]
> sorry, I know the reason.

Do you mind sharing the cause of the issue?

**Comment by a0709** [comment]
> > sorry, I know the reason.
> 
> Do you mind sharing the cause of the issue?

code like this:

`
func RedisDistributedLockV2() {
	// 创建 Redis 客户端
	client := redis.NewClient(&redis.Options{
		Addr: "localhost:6379",
	})

	// 创建 redsync 实例
	pool := goredis.NewPool(client)
	rs := redsync.New(pool)
	// 创建一个 mutex 实例
	mutex := rs.NewMutex("my-global-mutex",
		redsync.WithExpiry(10*time.Second),
		redsync.WithTries(100))
	for {
		// 获取锁
		if err := mutex.Lock(); err != nil {
			fmt.Println("Lock wait")
			// time.Sleep(3 * time.Second)
			continue
		}
		fmt.Println("Lock acquired")

		// 设置续期周期（例如：每 2 秒续期一次）
		ticker := time.NewTicker(5 * time.Second)

		ctx, canel := context.WithCancel(context.Background())

		// 启动一个 goroutine 进行续期
		go func() {
			defer ticker.Stop()
			for {
				select {
				case <-ticker.C:
					if ok, err := mutex.Extend(); !ok || err != nil {
						fmt.Println("Failed to extend lock:", err, " ", ok)
						continue
					}
					fmt.Println("Lock extended")
				case <-ctx.Done():
					fmt.Println("Lock extended end")
					return
				}
			}
		}()

		// 模拟一些业务逻辑
		time.Sleep(10 * time.Second)

		// 先停止续期，再释放锁
		canel()

		// 释放锁
		if ok, err := mutex.Unlock(); !ok || err != nil {
			fmt.Println("Failed to release lock:", err)
		} else {
			fmt.Println("Lock released")
		}
	}
}
`


This way of writing will cause the lock to be released, but it will also trigger a renewal. 'ctx.Done()'  may be executed at the same time as 'ticker.C', resulting in an extra renewal.
