### ISSUE TITLE
How about random delay time when acquire failed？

### ISSUE THREAD

**Issue by Astone-Chou** [go-redsync/redsync#16]

**Comment by MaruHyl** [comment]
I agree.
From redis doc : "When a client is unable to acquire the lock, it should try again after a random delay in order to try to desynchronize multiple clients trying to acquire the lock for the same resource at the same time (this may result in a split brain condition where nobody wins)"

**Comment by theodesp** [comment]
Isn't that handled via `DelayFunc`?

**Comment by hjr265** [comment]
@Astone-Chou You can define your own `DelayFunc`.
