### ISSUE TITLE
Can I acquire the lock and release lock in different goroutines?

### ISSUE THREAD

**Issue by livingston0318** [go-redsync/redsync#162]
I have a scenario that will acquire mutex in a API, and then push a task into task queue.
At the same time, I have a background goroutine to handle the task popped out from the task queue, after task finished, then this goroutine will release the lock, could it work with redsync?

It would be great if you share some best practice like the scenario I described.

**Comment by livingston0318** [comment]
if I run WithValue function when get a new mutex, would the default genValueFunc work? what's the priority?

**Comment by hjr265** [comment]
@livingston0318 You can use the `WithValue` option for this purpose.

The `genValueFunc` is used to generate a new value when attempting to acquire a lock. During unlock the value already generated or set with `WithValue` is used.

**Comment by livingston0318** [comment]
I was meant to acquire the key and set the val as I want, but it seems not work for redsync
