### ISSUE TITLE
Do not make "github.com/gomodule/redigo/redis" as a dep?

### ISSUE THREAD

**Issue by adanteng** [go-redsync/redsync#18]
Hello

I think make "github.com/gomodule/redigo/redis" as a hard dep is ok, but not flexible.

You can design a interface which demand the app to implement some redis func to complete the lock job. And still, you can use "github.com/gomodule/redigo/redis" to implement a example for the interface.

Thanks

**Comment by hjr265** [comment]
This one is now done in v3.
