### ISSUE TITLE
func acquire return value

### ISSUE THREAD

**Issue by JingFaC** [go-redsync/redsync#19]
func (m *Mutex) acquire(pool Pool, value string) bool {
	conn := pool.Get()
	defer conn.Close()
	reply, err := redis.String(conn.Do("SET", m.name, value, "NX", "PX", int(m.expiry/time.Millisecond)))
	return err == nil && reply == "OK"
}

when the function pool.Get() occur error(redis dowm or others) , but from this function i did not know the  real  happen ,mutex  unusable or redis cant be connected ? because it return a bool value.

**Comment by MaruHyl** [comment]
Imagine now there are many redis nodes you try to lock, some is ok, some is down, what shoud return?

**Comment by mingshun** [comment]
I also encounter this several times in production environment. My code log the error which returns from  `Mutex.Lock()` function, but it tell nothing about the error. It confuses me so many times. Also my code is run on a scratch docker image without any system facilities, I waste lots of time to figure out the reason every time when failing to acquire lock. 

If you can not return error from `Mutex.acquire(Pool, string)` function, can you log the error which returns from `redis.String(conn.Do("SET", m.name, value, "NX", "PX", int(m.expiry/time.Millisecond)))` that at least tell some useful information when error occurs.

**Comment by dcormier** [comment]
> Imagine now there are many redis nodes you try to lock, some is ok, some is down, what shoud return?

@MaruHyl, if the lock was acquired on enough nodes to have a quorum, return no error. Otherwise, return the error(s) encountered. This is the approach in #45.
