### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by knadh** [go-redsync/redsync#21]
Can there be a new release (that incorporates the change to `gomodule/redigo`)? The new Go 1.11 modules picks up the version from 2016, creating conflicting dependencies

**Comment by sneko** [comment]
@hjr265 

That's pretty annoying the main repo is no longer maintained.

Maybe you should propose to give rights to someone volunteer?

**Comment by hjr265** [comment]
@knadh @sneko A new release has been created. I am sorry for taking a while to get this done.

**Comment by sneko** [comment]
@hjr265 no problem 😃 thank you for maintaining the project 👍
