### ISSUE TITLE
Add interface for Mutex

### ISSUE THREAD

**Issue by gephaest** [go-redsync/redsync#22]
Usally Mutex struct pass into application layer structs, that should be covered by tests. So it will be conveniently if library will provide interface 
```golang
type Mutex interface {
	Lock() error
	Unlock() bool
	Extend() bool
}
```

**Comment by hjr265** [comment]
@gephaest Just to better understand your thought here: why not define it in the application where the mutex is being used?

**Comment by dcormier** [comment]
> why not define it in the application where the mutex is being used?

That is [the usual guidance](https://github.com/golang/go/wiki/CodeReviewComments#interfaces).
