### ISSUE TITLE
Support for Sentinel?

### ISSUE THREAD

**Issue by sneko** [go-redsync/redsync#24]
Hi,

I'm using a cluster of 3 sentinels and 3 redis instances and I was wondering if redsync plans to support Sentinel automatically, or should I reach Sentinel directly before giving the master IP to this library?

Thank you,

**Comment by sneko** [comment]
Since redsync uses redigo as Redis client, I guess I should focus on https://github.com/FZambia/sentinel

It seems I could create the redis.Pool with this library (https://godoc.org/github.com/FZambia/sentinel#Sentinel), and then inject it inside the redsync constructor.

Need to give a try as soon as I can 👍 . Do not hesitate to share your thoughts

**Comment by hjr265** [comment]
@sneko Did you have a chance to give this a try? How did it go? I am interested to know how that might have gone on your end before experimenting any changes in the library.

**Comment by maeglindeveloper** [comment]
@hjr265 , I gave it a try, and yes it works really well :).
