### ISSUE TITLE
Dependencies issues "github.com/garyburd/redigo/redis"

### ISSUE THREAD

**Issue by maeglindeveloper** [go-redsync/redsync#25]
Hi everyone, 

I see that the **"github.com/garyburd/redigo/redis"** dependencies is not anymore in the `redsync` code and has been replace by the gomodule one. But it does not seem to be released. 

Do you have any idea when it will be the case?
It is still causing some issue on my side:
```
D:\dev\go\pkg\mod\github.com\garyburd\redigo@v2.0.0+incompatible\redis\pool.go:28:2: use of internal package github.com/gomodule/redigo/internal not allowed
```
Thanks in advance! 👍 

@hjr265

**Comment by hjr265** [comment]
A new release has been created. That should solve this issue.
