### ISSUE TITLE
Consider update to touchScript

### ISSUE THREAD

**Issue by kamronbatman** [go-redsync/redsync#29]
https://github.com/go-redsync/redsync/blob/89538344de92e78df4b7eeeceec1f3cf2d7c0aeb/mutex.go#L135-L141

I would consider changing the touch script to be in line with the rest of the algorithm using:
```go
var touchScript = redis.NewScript(1, `
	if redis.call("GET", KEYS[1]) == ARGV[1] then
		return redis.call("pexpire", KEYS[1], ARGV[2])
	else
		return 0
	end
`)
```

If `pexpire` attempts to set the expiry of an unset key, then it will return 0.

**Comment by hjr265** [comment]
@kamronbatman That's interesting. I didn't know about this particular behavior of PEXPIRE.

Would you be willing to send a PR for this? Otherwise, I can get to this and the rest of the issues after this weekend.
