### ISSUE TITLE
Question regarding nodem (sync.Mutex)

### ISSUE THREAD

**Issue by kamronbatman** [go-redsync/redsync#30]
https://github.com/go-redsync/redsync/blob/025669a361d2f06ab6c5742f005877b971c2401a/mutex.go#L37

I am confused as to why a sync.Mutex is needed. Is it the case that the same Mutex struct pointer might be passed between goroutines? If this is a concern, I would argue it is an anti-pattern to do that in implementation.

I bring it up because it is an unnecessary overhead if it is in fact an existential safety precaution.

**Comment by kamronbatman** [comment]
I think if Pools are used properly, this is not needed?

**Comment by hjr265** [comment]
@kamronbatman You are right. This should not really be necessary.

I think we can get rid of it. I just need to test this a bit and tweak as necessary. But yes, I agree with you: having this lock isn't ideal.

**Comment by bysir-zl** [comment]
Here's another trap.

if u Lock twice, the Unlock will "deadlock" until timeout.

repetition code like this

```

func TestWithLock2(t *testing.T) {
	count := 0
	mutex := lock.RedSync.NewMutex("2")

	var wg sync.WaitGroup
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go func(i int) {
			err := mutex.Lock()

			log.Infof("lock")
			if err != nil {
				panic(err)
			}

			count += 10
			mutex.Unlock()
			// print when timeout (8s)
			log.Infof("unlock")
			wg.Done()
		}(i)
	}
	wg.Wait()

	if count != 10*10 {
		t.Fatal(count)
	}

	t.Log("ok")
}

```

I think you should attach importance to this issue.

**Comment by bysir-zl** [comment]
Or tell the user not to do so.

**Comment by kamronbatman** [comment]
Good catch. I think the solution to that issue is separate though? Maybe a flag to make additional locks no-op until unlock or expiration?

**Comment by bysir-zl** [comment]
> Sorry, I don't quite understand you. My English is not good, hhhh.

remove "m.nodem.Lock()" can avoid this problem. But I'm not sure if it will cause other problems.

ps: I think it's reasonable to reuse redsync.Mutex in a program. Because New it is an unnecessary overhead.

**Comment by bysir-zl** [comment]
Hello, do you have other solution to achieve distributed lock? This project is use "for {int i < reties}" to wait lock ,I don't think it's elegant enough. thx ;D

**Comment by kamronbatman** [comment]
The nature of redlock does not include reuse of the same lock object and in fact it implies that locks should be unique per use. The _only_ proper usage of redsync is to reuse the lock after it has been unlocked/expired (it is free), or create a new object.  This implies you cannot use the same lock in multiple go routines.

**Comment by bysir-zl** [comment]
Wait till I have time to explore, Thank you for your advice. 😆

**Comment by kamronbatman** [comment]
@hjr265, should I submit a PR to remove the sync?

**Comment by hjr265** [comment]
@kamronbatman That would be wonderful. Otherwise, I will be able to get to this some time the weekend after this.

**Comment by whiten** [comment]
I found this issue after running into a data race in my codebase caused by the removal of this internal lock. The cross-goroutine access in my case was to call `.Extend[Context]()` on a periodic basis so that a `redsync/v4.Mutex` could be held valid by a server as long as it is alive and the caller's context uncancelled, but able to be acquired by a different server fairly soon if the first stopped extending the lock's validity. I believe a goroutine is an appropriate way to implement such validity extensions, and so was surprised to learn that there isn't internal lock safety.

**Comment by kamronbatman** [comment]
I haven't dived into this code since 2020, but I'll try to understand your issue. Are you setting up the same scenario as @bysir-zl  here? https://github.com/go-redsync/redsync/issues/30#issuecomment-472808315

If so then my reply outlined a way to handle that, or outright explained that I am not sure this library is set up to handle that scenario. With that said, it has been 5 years and things may have changed. So I'll defer to @hjr265 to comment.

Additionally, i would love to see (if possible), a test scenario to replicate this race condition so we can address it appropriately.

**Comment by whiten** [comment]
I'll work on a repro in a bit, but in my use case a single goroutine creates, locks, periodically validates ownership (with `ExtendContext()`), and then unlocks a given mutex, but kicks off a second goroutine to continue extending the validity of the lock with `ExtendContext()`, and those two goroutines were identified by the Go race detector to race on fields inside of `ExtendContext()`. I can wrap a`redsync.Mutex` in another structure that makes it thread-safe with a `sync.Mutex`, but I think it would be more correct for that to be internal. To me, the overhead of a `sync.Mutex` feels low compared to the network operations behind the distributed locks this package offers.

I agree most calls shouldn't race against one another in proper uses, but `Extend()` (or `Extend() in conjunction with `Until()`) feel like cases where safe concurrent use should be permitted.
