### ISSUE TITLE
Include Usage Example

### ISSUE THREAD

**Issue by marwan-at-work** [go-redsync/redsync#31]
It would be great if there was a simple usage example whether on the README or godoc. Thanks

**Comment by kamronbatman** [comment]
I used one of the PR's to make an example.  I'll be honest, I haven't tested it yet, but this is what I am going to use.

```go
package redsync

import (
	"github.com/gomodule/redigo/redis"
	"github.com/go-redsync/redsync"
	"os"
	"time"
)

var Redsync *redsync.Redsync

func createPool(url string) *redis.Pool {
	return &redis.Pool{
		MaxIdle: 10,
		IdleTimeout: 180 * time.Second, // Default is 300 seconds for redis server
		Dial: func() (redis.Conn, error) {
			return redis.Dial("tcp", url)
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")
			return err
		},
	}
}

func init() {
	pools := []redsync.Pool{
		createPool(os.Getenv("REDIS_URL")),
	}

	Redsync = redsync.New(pools)
}
```

**Comment by cikupin** [comment]
hi @marwan-at-work I've just created an implementation of this redsync in my repo https://github.com/cikupin/redis-mutex-lock

It's not a perfect implementation. If you have suggestion, please leave an issue

**Comment by kamronbatman** [comment]
@cikupin, I am curious, what were you trying to solve that required a new implementation?
Also regarding your repo, how come you have redsync too?

**Comment by cikupin** [comment]
@kamronbatman it's not a new implementation of redysnc. It's just an example usage. 
I tried to add example usages for both redsync and redislock in my repo.
