### ISSUE TITLE
Why 2 milliseconds is added to the expire time in the function "Lock"?

### ISSUE THREAD

**Issue by ahrtr** [go-redsync/redsync#37]
I don't understand why 2 milliseconds is added to the variable "until" in the function "Lock".
`until := time.Now().Add(m.expiry - time.Now().Sub(start) - time.Duration(int64(float64(m.expiry)*m.factor)) + 2*time.Millisecond)`

Based on the following post https://redis.io/topics/distlock, the safety expire time is calculated as below,
`MIN_VALIDITY=TTL-(T2-T1)-CLOCK_DRIFT`

So the correct formula should be as below, what did I miss?
`until := time.Now().Add(m.expiry - time.Now().Sub(start) - time.Duration(int64(float64(m.expiry)*m.factor)))`

**Comment by kamronbatman** [comment]
The calculation I use on my private fork is this:
```
		end := time.Now()
		validTime := m.expiry - end.Sub(start) - time.Duration(int64(float64(m.expiry) * m.factor))
		if n >= m.quorum && validTime > 0 {
```
Very similar, so I agree it should not be needed.

**Comment by hjr265** [comment]
@ahrtr @kamronbatman Thanks for pointing this out. The unnecessary 2ms has been removed.
