### ISSUE TITLE
Does it work with go modules?

### ISSUE THREAD

**Issue by cupen** [go-redsync/redsync#39]
```bash
$ go version                      
go version go1.12.6 linux/amd64

$ export GO111MODULE=on
$ mkdir foobar && cd foobar
$ go mod init foobar
go: creating new go.mod: module foobar

$ go get gopkg.in/redsync.v1
go: gopkg.in/redsync.v1@v1.2.0: go.mod has non-....v1 module path "github.com/go-redsync/redsync" at revision v1.2.0
go: error loading module requirements

```

**Comment by kamronbatman** [comment]
I use it with go modules and haven't had an issue, but I let it pull directly from the repository, not v1.2.0 (since that is also out of date).
My go.mod shows:
`github.com/vyng/redsync v0.0.0-20190528225357-5764434a66bb`

**Comment by kamronbatman** [comment]
I use it with go modules and haven't had an issue, but I let it pull directly from the repository, not v1.2.0 (since that is also out of date).

**Comment by cupen** [comment]
You are right. It's ok with using `github.com/go-redsync/redsync` directly.
