### ISSUE TITLE
v1.4.1 not following semver

### ISSUE THREAD

**Issue by bombsimon** [go-redsync/redsync#48]
According to [semver.org](https://semver.org) updating MINOR version should be made when "*you add functionality in a backwards compatible manner*" and if you are making breaking changes you must update MAJOR version.

In commit fb51a7f the signature for `Unlock()` got changed which means that it introduces a breaking change. I noticed this while updating dependencies for an application using a third party library which in turn is using `redisync`. If you're not the author of every package in the dependency chain this means that you can no longer run `go get -u all` to update your dependencies.

I suggest releasing a `v1.4.2` tag from 98bb566 and then bump this library to `v2.0.0` and create a new release with the new signature from `master`.

**Comment by hjr265** [comment]
Thank you, @bombsimon. Your suggestion has been implemented.

v2.0.0 now has the latest code. And, v1.4.2 has the last working code without any breaking changes.

**Comment by bombsimon** [comment]
Wow, that was fast! Thanks!
