### ISSUE TITLE
Redigo version

### ISSUE THREAD

**Issue by bancek** [go-redsync/redsync#53]
Why is `redsync` using `github.com/gomodule/redigo v2.0.0+incompatible`.

`v2.0.0` branch was last updated `14 Mar 2018` and does not seem to be maintained. All new development is happening on `v1` (e.g. `v1.8.2` was released `8 Jun 2020`).

I don't know to force my project to use `redsync` with `redigo@v1.8.2` without forking `redsync` and fixing `go.mod`.

**Comment by bancek** [comment]
I've changed the version to `v1.8.2` in [my fork](https://github.com/bancek/redsync/commit/7a737502eb709c5198df90f32bcf61302a5f140f) and all tests pass.

I understand that this is a breaking change for users of `redsync` but maybe you could create a version `v4` and change the `redigo` version to `v1.8.2` so it gets all the bug fixes and improvements.

**Comment by hjr265** [comment]
@bancek I would like to merge #54 and #55 as well to this future v4. Would you be interested in sending a pull request with your patch based on top of #55?

**Comment by bancek** [comment]
Done.
