### ISSUE TITLE
Comments about runtime errors appear invalid

### ISSUE THREAD

**Issue by stevenh** [go-redsync/redsync#7]
Both Unlock and Extend state its a runtime error if the lock isn't held, however given locks can timeout its impossible to know if we hold the lock.

Also looking at the code I can't see any way we can get runtime error from this case.

Finally I've tried calling mtx.Unlock() multiple times as well as mtx.Extend() after mtx.Unlock() and no runtime error occurred.

Given the evidence I believe the docs are inaccurate and the reference to runtime errors should be removed.

**Comment by hjr265** [comment]
Thank you, @stevenh. The comments have been updated.
