### ISSUE TITLE
cluster client and pool

### ISSUE THREAD

**Issue by yejkk** [go-redsync/redsync#70]
The pool means a redis instance? If I use redis cluster client and it has five nodes，the redis cluster is a pool or a master node is a pool.

**Comment by yejkk** [comment]
I want to know how Redis Cluster solves the problem of data lost after a crash. Now I know Redis Cluster [not able to guarantee strong consistency](https://redis.io/topics/cluster-tutorial).

**Comment by hjr265** [comment]
> The pool means a redis instance? If I use redis cluster client and it has five nodes，the redis cluster is a pool or a master node is a pool.

The cluster is a pool. Where the data of the lock goes in the cluster depends on its configuration.

> I want to know how Redis Cluster solves the problem of data lost after a crash.

You will want to refer to Redis' documentation for that.

**Comment by vmcqgo** [comment]
Since the pool is expecting a `*redis.Client` and not a `*redis.ClusterClient` it looks like it does not support cluster Redis?

```
type pool struct {
	delegate *redis.Client
}
```

https://pkg.go.dev/github.com/go-redis/redis?utm_source=godoc#NewClusterClient
