### ISSUE TITLE
Potential bug of ValidContext/Valid

### ISSUE THREAD

**Issue by KeiichiHirobe** [go-redsync/redsync#72]
I think there is a potential bug in current implementation of `ValidContext/Valid`. 
When `ValidContext/Valid` returns true, there is a possibility that the lock is expired already.
For example, case N=5, we have 3 seconds before lock expires, even if 4 nodes responds soon(~100ms) , it is possibility that the last node needs 10 seconds to respond, and if that happens, `ValidContext/Valid` returns true, but lock is expired.

As far as I read https://redis.io/topics/distlock, I understand we should trust only the value of `until`. 

> If the lock was acquired, its validity time is considered to be the initial validity time minus the time elapsed, as computed in step 3.

So, if https://github.com/go-redsync/redsync/pull/71 merged, It may be a good idea to make `ValidContext/Valid` deprecated and client can check by calling `Until` or change implementation like below  to keep backward compatibility.

```
func (m *Mutex) Valid() (bool, error) {
	return time.Now().Before(until), nil
}
```

**Comment by hjr265** [comment]
Sounds good to me. Will add a deprecation note to the Godoc for the functions.

**Comment by okhowang** [comment]
When someone delete mutex's key in redis directly (not from redsync library).
`Valid` can detect the situation, but `Until` can't.
Maybe we need a `ValidUtil` do `GET` and `TTL`?

**Comment by netixx** [comment]
Also for an external observer (say a controller), who want's to check if the lock has been acquired or not, Valid is the only way to fetch the lock from redis, without attempting to lock it, right ?
