### ISSUE TITLE
Failing to release lock without any error

### ISSUE THREAD

**Issue by ami-m** [go-redsync/redsync#81]
Hi, 
I had this problem on 4.4.1 and still have it on 4.5.0 :

mutex.Unlock occasionally returns success=false and err=nil
The lack of error makes it hard to investigate my bug (I'm assuming there is something wrong in how I use it)

This is my code (it runs in a goroutine):
```
const maxWorkTimeOnBuffer = 5 * time.Second
lockKey := fmt.Sprintf("buffer:ticklock:%d", (*bfr).GetDeviceId())
mutex := rs.NewMutex(lockKey, redsync.WithExpiry(maxWorkTimeOnBuffer), redsync.WithTries(1))
if lockFail := mutex.Lock(); lockFail != nil {
	log.Trace("someone else already has ", lockKey)
	return
}

// release the lock after we're done
defer func(mutex *redsync.Mutex) {
	success, err := mutex.Unlock()
	if !success {
		log.WithError(err).Errorf("failed to release tick lock on buffer %d", (*bfr).GetDeviceId())
	}
}(mutex)
```

and after that is unrelated code

**Comment by sanjay20** [comment]
Recently I started using red sync, if first request holding a lock and yet to release and 2nd request attempt to lock it's just block for approx 6 seconds. How to make 2nd request wait till first request release lock ?

**Comment by iamatsundere** [comment]
@ami-m did you fix that issue? I have the same problem

**Comment by ami-m** [comment]
sadly, no

**Comment by SinowZ** [comment]
I met this issue also.
