### ISSUE TITLE
When first thread acquired a lock ,second thread should wait till first thread release a lock

### ISSUE THREAD

**Issue by sanjay20** [go-redsync/redsync#82]
I recently started using redsync  in my go applications .I am looking for locking when first request acquired a lock and not released yet and 2nd request tried to acquire a lock it should wait or block  till first request release a lock but seems like 2nd request wait for approx 6 seconds only and returns.

Is there any way to block second request till first request release a lock ?

**Comment by BananZG** [comment]
perhaps you may try setting custom expiry and retryDelay to make the delay longer?

If you check the source code of this library, you may customise it like for example,
make the lock expiry time 180 seconds (default 8 seconds)
and try with linear retry for every 5 seconds (default is retrying every few random ms) and default max 32 retries

`mutex := rs.NewMutex("YOUR-KEY", redsync.WithExpiry(180*time.Second), redsync.WithRetryDelay(5*time.Second))`
