### ISSUE TITLE
如何获取 使用WithValue 设置的锁的Value，以及为什么在获取锁失败时，无法获取真实的value？比如业务需要获取value来记录是谁（节点）占用了锁

### ISSUE THREAD

**Issue by abelbinguo** [go-redsync/redsync#85]
```
mutex3 := rs.NewMutex(key, WithValue("this is test value"))
mutex3.Lock()
So(mutex3.Value(), ShouldEqual, "this is test value")
```
-- false
Expected: 'this is test value'
Actual: 'ndPqnC9nNbxA8dZ1snfc+w=='

**Comment by hjr265** [comment]
@abelbinguo I think the documentation can be improved around this.

The `WithValue` option is meant to "transfer" the lock's ownership. Calling Lock will regenerate the internal value and override what `Mutex.Value()` returns.

If you want to use a predefined value, please use the `WithGenValueFunc` option. This option allows you to control how the internal value is generated. You can do something like this for a static internal value:

``` go
NewMutex(name, WithGenValueFunc(func() (string, error) { return "value", nil }))
```
