### ISSUE TITLE
Install link for Redsync not working for me

### ISSUE THREAD

**Issue by RKTMN** [go-redsync/redsync#9]
The following command given did not install Redsync for me:
$ go get gopkg.in/redsync.v1

Instead, I had to use the following command, which seems to have worked:
```go get github.com/go-redsync/redsync```

Is this a known problem? Was it just a problem for me? Does the README need an update?

**Comment by javeria2** [comment]
Wasn't a problem for me. I just tried `go get gopkg.in/redsync.v1` and it seemed to work just fine

**Comment by hjr265** [comment]
@RKTMN Are you using Go modules?
